"""AUTO-GENERATED by scripts/translate_i18n.py — Spanish/French overlay.

Merged into utils.i18n.TRANSLATIONS at import. Regenerate with:
    python -m scripts.translate_i18n
"""

EXTRA = {
    "nav_for_sellers": {
        "es": "Para vendedores",
        "fr": "Pour les vendeurs"
    },
    "nav_for_investors": {
        "es": "Para inversores",
        "fr": "Pour les investisseurs"
    },
    "nav_how_it_works": {
        "es": "Cómo funciona",
        "fr": "Comment ça marche"
    },
    "nav_pricing": {
        "es": "Precios",
        "fr": "Tarification"
    },
    "nav_contact": {
        "es": "Contacto",
        "fr": "Contact"
    },
    "nav_get_quote": {
        "es": "Obtener una cotización",
        "fr": "Obtenir un devis"
    },
    "nav_login": {
        "es": "Iniciar sesión",
        "fr": "Se connecter"
    },
    "hero_eyebrow": {
        "es": "Financiamiento de facturas para empresas en crecimiento",
        "fr": "Financement de factures pour les entreprises en croissance"
    },
    "hero_turn": {
        "es": "Convierta ",
        "fr": "Transformez "
    },
    "hero_unpaid": {
        "es": "facturas impagas ",
        "fr": "factures impayées "
    },
    "hero_into": {
        "es": "en ",
        "fr": "en "
    },
    "hero_working": {
        "es": "capital de trabajo ",
        "fr": "capital de roulement "
    },
    "hero_for_biz": {
        "es": "para su negocio.",
        "fr": "pour votre entreprise."
    },
    "hero_lede": {
        "es": "Factorio conecta empresas que necesitan flujo de caja ahora con inversores que buscan retornos a corto plazo respaldados por activos. Suba su factura, obtenga financiamiento en días y concéntrese en hacer crecer su negocio — no en perseguir pagos.",
        "fr": "Factorio connecte les entreprises qui ont besoin de trésorerie maintenant avec des investisseurs à la recherche de rendements à court terme adossés à des actifs. Téléchargez votre facture, obtenez un financement en quelques jours et concentrez-vous sur la croissance de votre entreprise — pas sur la poursuite des paiements."
    },
    "hero_cta_finance": {
        "es": "Financiar una factura",
        "fr": "Financer une facture"
    },
    "hero_cta_invest": {
        "es": "Invertir ahora",
        "fr": "Investir maintenant"
    },
    "stat_advance": {
        "es": "tasa de anticipo en facturas verificadas",
        "fr": "taux d’avance sur factures vérifiées"
    },
    "stat_days": {
        "es": "desde el envío hasta el financiamiento",
        "fr": "de la soumission au financement"
    },
    "stat_sectors": {
        "es": "sectores industriales admitidos",
        "fr": "secteurs d’activité pris en charge"
    },
    "stat_total": {
        "es": "idiomas — totalmente localizable",
        "fr": "langues — entièrement localisable"
    },
    "how_eyebrow": {
        "es": "Cómo funciona",
        "fr": "Comment ça marche"
    },
    "how_heading": {
        "es": "De la factura al efectivo en cuatro pasos.",
        "fr": "De la facture à l’argent en quatre étapes."
    },
    "how_s1_title": {
        "es": "Envíe su factura",
        "fr": "Soumettez votre facture"
    },
    "how_s1_body": {
        "es": "Suba una factura verificada con plazos de pago de 15–180 días. Su cliente debe haber recibido los bienes o el servicio.",
        "fr": "Téléchargez une facture vérifiée avec des conditions de paiement de 15 à 180 jours. Votre client doit avoir reçu les biens ou le service."
    },
    "how_s2_title": {
        "es": "Verificamos los detalles",
        "fr": "Nous vérifions les détails"
    },
    "how_s2_body": {
        "es": "Factorio confirma la factura con su cliente y evalúa el riesgo. Tiempo de respuesta habitual: 24 horas.",
        "fr": "Factorio confirme la facture auprès de votre client et évalue le risque. Délai habituel : 24 heures."
    },
    "how_s3_title": {
        "es": "Obtenga financiamiento de inversores",
        "fr": "Obtenez un financement par des investisseurs"
    },
    "how_s3_body": {
        "es": "Su factura se publica en nuestro mercado. Los inversores la financian con una tasa de anticipo de hasta el 90 %. El efectivo llega a su cuenta en 1–3 días.",
        "fr": "Votre facture est listée sur notre marketplace. Les investisseurs la financent à un taux d’avance pouvant atteindre 90 %. Les fonds arrivent sur votre compte en 1 à 3 jours."
    },
    "how_s4_title": {
        "es": "Liquidación y rendimientos",
        "fr": "Règlement et rendements"
    },
    "how_s4_body": {
        "es": "Cuando su cliente paga la factura, los inversores reciben su capital más los rendimientos. Usted recibe el saldo restante menos las comisiones.",
        "fr": "Lorsque votre client paie la facture, les investisseurs reçoivent leur capital plus les rendements. Vous recevez le solde restant moins les frais."
    },
    "sectors_eyebrow": {
        "es": "Sectores que financiamos",
        "fr": "Secteurs que nous finançons"
    },
    "sectors_heading": {
        "es": "Soluciones de flujo de caja en todas las industrias.",
        "fr": "Solutions de trésorerie dans tous les secteurs."
    },
    "sector_manufacturing": {
        "es": "Manufactura",
        "fr": "Industrie manufacturière"
    },
    "sector_wholesale": {
        "es": "Mayorista",
        "fr": "Commerce de gros"
    },
    "sector_construction": {
        "es": "Construcción",
        "fr": "Construction"
    },
    "sector_logistics": {
        "es": "Logística",
        "fr": "Logistique"
    },
    "sector_services": {
        "es": "Servicios empresariales",
        "fr": "Services aux entreprises"
    },
    "sector_manufacturing_blurb": {
        "es": "Convierta ciclos de pago largos en capital de trabajo inmediato para materias primas y producción.",
        "fr": "Transformez les cycles de paiement longs en capital de roulement immédiat pour les matières premières et la production."
    },
    "sector_wholesale_blurb": {
        "es": "Cierre la brecha entre los pagos a proveedores y los cobros de clientes en la distribución.",
        "fr": "Comblez l’écart entre les paiements aux fournisseurs et les recettes clients dans la distribution."
    },
    "sector_construction_blurb": {
        "es": "Financie facturas por hitos para que su equipo siga trabajando sin interrupciones de flujo de caja.",
        "fr": "Financez les factures d’étape pour que votre équipe continue de travailler sans rupture de trésorerie."
    },
    "sector_logistics_blurb": {
        "es": "Mantenga los camiones en movimiento y los almacenes abastecidos mientras los clientes liquidan en sus términos.",
        "fr": "Gardez les camions en mouvement et les entrepôts approvisionnés pendant que les clients règlent à leurs conditions."
    },
    "sector_services_blurb": {
        "es": "Consultoría, personal, TI — reciba el pago ahora por el trabajo que entregó el mes pasado.",
        "fr": "Conseil, intérim, IT — soyez payé maintenant pour le travail livré le mois dernier."
    },
    "sector_hospitality": {
        "es": "Hostelería",
        "fr": "Hôtellerie-Restauration"
    },
    "sector_retail": {
        "es": "Comercio minorista",
        "fr": "Commerce de détail"
    },
    "sector_healthcare": {
        "es": "Salud",
        "fr": "Santé"
    },
    "sector_agriculture": {
        "es": "Agricultura",
        "fr": "Agriculture"
    },
    "sector_energy": {
        "es": "Energía",
        "fr": "Énergie"
    },
    "sector_hospitality_blurb": {
        "es": "Suavice los ciclos de efectivo estacionales para hoteles, restaurantes y sus proveedores.",
        "fr": "Lissez les cycles de trésorerie saisonniers pour les hôtels, restaurants et leurs fournisseurs."
    },
    "sector_retail_blurb": {
        "es": "Financie inventario y cubra los términos de proveedores mientras los recibos se ponen al día.",
        "fr": "Financez les stocks et comblez les délais fournisseurs pendant que les recettes rattrapent."
    },
    "sector_healthcare_blurb": {
        "es": "Financie las cuentas por cobrar lentas de aseguradoras e instituciones para clínicas y proveedores.",
        "fr": "Financez les créances lentes des assureurs et institutions pour cliniques et fournisseurs."
    },
    "sector_agriculture_blurb": {
        "es": "Cubra la brecha entre la cosecha, la entrega y el pago del comprador.",
        "fr": "Comblez l'écart entre récolte, livraison et paiement de l'acheteur."
    },
    "sector_energy_blurb": {
        "es": "Financie las cuentas por cobrar de servicios públicos, contratistas y ciclos de proyectos largos.",
        "fr": "Financez les créances des services publics, entrepreneurs et longs cycles de projets."
    },
    "sector_explorer_eyebrow": {
        "es": "Explore su sector",
        "fr": "Explorez votre secteur"
    },
    "sector_explorer_heading": {
        "es": "Vea cómo funciona en su industria.",
        "fr": "Voyez comment cela fonctionne dans votre industrie."
    },
    "sector_explorer_label": {
        "es": "Elija una industria",
        "fr": "Choisissez une industrie"
    },
    "sector_manufacturing_usecase": {
        "es": "Un fabricante de piezas factura a un fabricante de automóviles en términos de 90 días y adelanta el 85% hoy para comprar materias primas para la próxima producción.",
        "fr": "Un fabricant de pièces facture un constructeur automobile à 90 jours et avance 85 % aujourd'hui pour acheter des matières premières pour la prochaine série."
    },
    "sector_wholesale_usecase": {
        "es": "Un distribuidor factoriza facturas a una cadena de supermercados para pagar a sus propios proveedores antes y obtener descuentos por volumen.",
        "fr": "Un distributeur factorise des factures pour une chaîne de supermarchés afin de payer ses fournisseurs plus tôt et obtenir des remises sur volume."
    },
    "sector_construction_usecase": {
        "es": "Un subcontratista financia un certificado de hito para poder pagar a los equipos y alquilar equipo antes de que pague el desarrollador.",
        "fr": "Un sous-traitant finance un certificat d'étape pour payer les équipes et louer du matériel avant que le promoteur ne paie."
    },
    "sector_logistics_usecase": {
        "es": "Un transportista de carga adelanta facturas a un minorista para cubrir combustible y salarios de conductores mientras corre el plazo de 60 días.",
        "fr": "Un transporteur de fret avance des factures à un détaillant pour couvrir le carburant et les salaires des conducteurs pendant le délai de 60 jours."
    },
    "sector_hospitality_usecase": {
        "es": "Un grupo hotelero ejecuta un programa de factoraje inverso para que 200 proveedores de alimentos y lencería reciban el pago antes — sin que el grupo rompa sus términos.",
        "fr": "Un groupe hôtelier gère un programme de reverse factoring pour que 200 fournisseurs de nourriture et linge soient payés plus tôt — sans que le groupe ne rompe ses conditions."
    },
    "sector_retail_usecase": {
        "es": "Un minorista factoriza facturas de proveedores antes de un pico estacional para abastecer estantes antes de que lleguen las ventas.",
        "fr": "Un détaillant factorise des factures fournisseurs avant un pic saisonnier pour approvisionner les rayons avant l'arrivée des ventes."
    },
    "sector_healthcare_usecase": {
        "es": "Un proveedor de suministros médicos adelanta facturas a clínicas mientras los reembolsos de aseguradoras se liquidan en 60–90 días.",
        "fr": "Un fournisseur de fournitures médicales avance des factures aux cliniques pendant que les remboursements des assureurs se règlent sur 60–90 jours."
    },
    "sector_services_usecase": {
        "es": "Una consultora de TI financia una factura de hito para hacer la nómina antes de que termine el plazo de 45 días del cliente empresarial.",
        "fr": "Un cabinet de conseil IT finance une facture d'étape pour faire la paie avant la fin du délai de 45 jours du client entreprise."
    },
    "sector_agriculture_usecase": {
        "es": "Un productor de granos adelanta facturas a un procesador para financiar la próxima siembra antes de que se pague el cultivo.",
        "fr": "Un producteur de céréales avance des factures à un transformateur pour financer la prochaine plantation avant que la récolte ne soit payée."
    },
    "sector_energy_usecase": {
        "es": "Un contratista solar financia cuentas por cobrar de una empresa de servicios públicos para financiar la próxima instalación a lo largo de un ciclo de proyecto largo.",
        "fr": "Un entrepreneur solaire finance des créances d'un service public pour financer la prochaine installation sur un long cycle de projet."
    },
    "benefits_eyebrow": {
        "es": "Por qué Factorio",
        "fr": "Pourquoi Factorio"
    },
    "benefits_heading": {
        "es": "Efectivo más rápido. Mejores rendimientos. Total transparencia.",
        "fr": "Trésorerie plus rapide. Meilleurs rendements. Transparence totale."
    },
    "benefit_sellers_label": {
        "es": "Para vendedores",
        "fr": "Pour les vendeurs"
    },
    "benefit_sellers_metric": {
        "es": "1–3 days",
        "fr": "1–3 days"
    },
    "benefit_sellers_caption": {
        "es": "desde el envío de la factura hasta el efectivo en su cuenta. No más esperar 30–90 días para el pago.",
        "fr": "de la soumission de la facture à l'argent sur votre compte. Plus d'attente de 30–90 jours pour le paiement."
    },
    "benefit_investors_label": {
        "es": "Para inversores",
        "fr": "Pour les investisseurs"
    },
    "benefit_investors_metric": {
        "es": "8–12% p.a.",
        "fr": "8–12% p.a."
    },
    "benefit_investors_caption": {
        "es": "rendimientos anualizados objetivo en activos respaldados por facturas de corta duración con calificación de riesgo transparente.",
        "fr": "rendements annualisés cibles sur des actifs adossés à des factures de courte durée avec notation de risque transparente."
    },
    "benefit_platform_label": {
        "es": "Plataforma",
        "fr": "Plateforme"
    },
    "benefit_platform_metric": {
        "es": "Multidivisa",
        "fr": "Multi-devises"
    },
    "benefit_platform_caption": {
        "es": "Fondee e invierta en EUR, USD, GBP y monedas locales. Diversifique entre sectores, grados de riesgo y duraciones.",
        "fr": "Financez et investissez en EUR, USD, GBP et devises locales. Diversifiez entre secteurs, notes de risque et durées."
    },
    "cta_eyebrow": {
        "es": "Comience",
        "fr": "Commencez"
    },
    "cta_headline": {
        "es": "¿Listo para desbloquear su flujo de efectivo?",
        "fr": "Prêt à débloquer votre trésorerie ?"
    },
    "cta_body": {
        "es": "Obtenga una cotización gratis en minutos. Sin compromiso, sin tarifas ocultas.",
        "fr": "Obtenez un devis gratuit en quelques minutes. Aucun engagement, aucuns frais cachés."
    },
    "cta_button": {
        "es": "Obtenga una cotización gratis",
        "fr": "Obtenir un devis gratuit"
    },
    "cta_browse": {
        "es": "Explorar el mercado",
        "fr": "Parcourir le marché"
    },
    "footer_tagline": {
        "es": "Financiamiento de facturas para empresas en crecimiento.",
        "fr": "Financement de factures pour les entreprises en croissance."
    },
    "footer_built_by": {
        "es": "Creado por un equipo que entiende que el flujo de caja es el alma de toda empresa en crecimiento.",
        "fr": "Créé par une équipe qui comprend que la trésorerie est le sang de toute entreprise en croissance."
    },
    "footer_product": {
        "es": "Producto",
        "fr": "Produit"
    },
    "footer_company": {
        "es": "Empresa",
        "fr": "Entreprise"
    },
    "footer_terms": {
        "es": "Términos",
        "fr": "Conditions"
    },
    "footer_privacy": {
        "es": "Privacidad",
        "fr": "Confidentialité"
    },
    "footer_marketplace": {
        "es": "Mercado",
        "fr": "Marché"
    },
    "sellers_eyebrow": {
        "es": "Para vendedores",
        "fr": "Pour les vendeurs"
    },
    "sellers_h1": {
        "es": "Reciba el pago ahora por el trabajo que ya ha realizado.",
        "fr": "Soyez payé maintenant pour le travail que vous avez déjà effectué."
    },
    "sellers_lede": {
        "es": "Deje de esperar a que las facturas se liquiden. Cargue una factura verificada y reciba hasta el 90% de su valor en 1–3 días hábiles. Cuando su cliente pague, obtendrá el saldo menos una pequeña comisión.",
        "fr": "Arrêtez d'attendre que les factures soient réglées. Téléchargez une facture vérifiée et recevez jusqu'à 90 % de sa valeur en 1 à 3 jours ouvrés. Lorsque votre client paie, vous recevez le solde moins des frais minimes."
    },
    "sellers_benefits_h2": {
        "es": "Cómo el financiamiento de facturas ayuda a su negocio.",
        "fr": "Comment le financement de factures aide votre entreprise."
    },
    "sellers_b1_title": {
        "es": "Crecimiento empresarial más rápido",
        "fr": "Croissance d'entreprise plus rapide"
    },
    "sellers_b1_body": {
        "es": "Contrate más personal y gane nuevos contratos sin esperar 30–90 días para el pago.",
        "fr": "Embauchez plus de personnel et remportez de nouveaux contrats sans attendre 30 à 90 jours pour le paiement."
    },
    "sellers_b2_title": {
        "es": "Mejores condiciones con proveedores",
        "fr": "Meilleures conditions fournisseurs"
    },
    "sellers_b2_body": {
        "es": "Muchos proveedores ofrecen descuentos por pago anticipado o temprano. Aproveche esos ahorros.",
        "fr": "De nombreux fournisseurs offrent des réductions pour un paiement anticipé ou précoce. Profitez de ces économies."
    },
    "sellers_b3_title": {
        "es": "Nómina eficiente",
        "fr": "Paie efficace"
    },
    "sellers_b3_body": {
        "es": "Pago rápido para empleados y subcontratistas, incluso cuando los clientes pagan tarde.",
        "fr": "Paiement rapide pour les employés et sous-traitants, même lorsque les clients paient en retard."
    },
    "sellers_b4_title": {
        "es": "Sin deuda en sus libros",
        "fr": "Aucune dette sur vos livres"
    },
    "sellers_b4_body": {
        "es": "El financiamiento de facturas no es un préstamo. Es un anticipo sobre el dinero que ya ha ganado.",
        "fr": "Le financement de factures n'est pas un prêt. C'est une avance sur l'argent que vous avez déjà gagné."
    },
    "sellers_eligibility_h2": {
        "es": "Criterios de elegibilidad.",
        "fr": "Critères d'éligibilité."
    },
    "sellers_e1": {
        "es": "Empresa registrada, operando por más de 6 meses",
        "fr": "Entreprise enregistrée, en activité depuis plus de 6 mois"
    },
    "sellers_e2": {
        "es": "Facturación anual mínima de 500M UZS",
        "fr": "Chiffre d'affaires annuel minimum de 500M UZS"
    },
    "sellers_e3": {
        "es": "Facturas con plazos de pago de 15–180 días",
        "fr": "Factures avec des conditions de paiement de 15 à 180 jours"
    },
    "sellers_e4": {
        "es": "Su cliente es una empresa que opera 3+ años con al menos 5B UZS de facturación anual",
        "fr": "Votre client est une entreprise en activité depuis 3 ans ou plus avec un chiffre d'affaires annuel d'au moins 5B UZS"
    },
    "sellers_cta_h": {
        "es": "Convierta sus facturas en efectivo hoy.",
        "fr": "Transformez vos factures en espèces dès aujourd'hui."
    },
    "sellers_cta_b": {
        "es": "Aplique en minutos. Reciba una oferta en 1–3 días hábiles. Sin compromiso.",
        "fr": "Postulez en quelques minutes. Recevez une offre en 1 à 3 jours ouvrés. Aucun engagement."
    },
    "investors_eyebrow": {
        "es": "Para inversores",
        "fr": "Pour les investisseurs"
    },
    "investors_h1": {
        "es": "Gane 8–12% en activos a corto plazo respaldados por facturas.",
        "fr": "Gagnez 8 à 12 % sur des actifs à court terme adossés à des factures."
    },
    "investors_lede": {
        "es": "Factorio le da acceso a una nueva clase de activos: facturas comerciales verificadas. Duración corta, precios transparentes y empresas reales al otro lado.",
        "fr": "Factorio vous donne accès à une nouvelle classe d'actifs : des factures commerciales vérifiées. Durée courte, tarification transparente et de vraies entreprises de l'autre côté."
    },
    "investors_why_h2": {
        "es": "¿Por qué el financiamiento de facturas?",
        "fr": "Pourquoi le financement de factures ?"
    },
    "investors_f1_title": {
        "es": "Duración corta",
        "fr": "Durée courte"
    },
    "investors_f1_body": {
        "es": "Los plazos típicos de facturas de 30–90 días significan que su capital no está bloqueado por años. Rotación rápida, reinversión frecuente.",
        "fr": "Les conditions de facturation typiques de 30 à 90 jours signifient que votre capital n'est pas bloqué pendant des années. Rotation rapide, réinvestissement fréquent."
    },
    "investors_f2_title": {
        "es": "Respaldado por activos",
        "fr": "Adossé à des actifs"
    },
    "investors_f2_body": {
        "es": "Cada inversión está respaldada por una factura comercial verificada de una empresa en operación. Cuentas por cobrar reales, no promesas.",
        "fr": "Chaque investissement est adossé à une facture commerciale vérifiée d'une entreprise en activité. De vraies créances, pas des promesses."
    },
    "investors_f3_title": {
        "es": "Calificación de riesgo transparente",
        "fr": "Notation de risque transparente"
    },
    "investors_f3_body": {
        "es": "Cada factura se califica de A–D según la solvencia del deudor, el historial de pagos y el riesgo del sector. Usted elige su apetito de riesgo.",
        "fr": "Chaque facture est notée de A à D en fonction de la solvabilité du débiteur, de l'historique de paiement et du risque sectoriel. Vous choisissez votre appétit pour le risque."
    },
    "investors_f4_title": {
        "es": "Diversificación",
        "fr": "Diversification"
    },
    "investors_f4_body": {
        "es": "Distribuya su capital entre sectores, geografías y grados de riesgo. Inversión mínima desde 500,000 UZS por factura.",
        "fr": "Répartissez votre capital entre secteurs, zones géographiques et niveaux de risque. Investissement minimum à partir de 500 000 UZS par facture."
    },
    "investors_how_h2": {
        "es": "Cómo funciona la inversión.",
        "fr": "Comment fonctionne l'investissement."
    },
    "investors_h_s1_title": {
        "es": "Explora el mercado",
        "fr": "Parcourir le marché"
    },
    "investors_h_s1_body": {
        "es": "Filtra facturas por sector, grado de riesgo, duración y rendimiento. Cada listado muestra el deudor, el vendedor y la evaluación completa de riesgo.",
        "fr": "Filtrez les factures par secteur, note de risque, durée et rendement. Chaque annonce affiche le débiteur, le vendeur et l'évaluation complète des risques."
    },
    "investors_h_s2_title": {
        "es": "Invierta desde 500K UZS",
        "fr": "Investissez à partir de 500K UZS"
    },
    "investors_h_s2_body": {
        "es": "Elige cuánto invertir en cada factura. Tus fondos se agrupan con otros inversores para alcanzar el objetivo de financiamiento.",
        "fr": "Choisissez combien investir dans chaque facture. Vos fonds sont mis en commun avec d'autres investisseurs pour atteindre l'objectif de financement."
    },
    "investors_h_s3_title": {
        "es": "Sigue tu cartera",
        "fr": "Suivez votre portefeuille"
    },
    "investors_h_s3_body": {
        "es": "Monitorea tus posiciones activas, fechas de liquidación esperadas y rendimientos acumulados en tiempo real.",
        "fr": "Surveillez vos positions actives, dates de règlement prévues et rendements cumulés en temps réel."
    },
    "investors_h_s4_title": {
        "es": "Recibe rendimientos",
        "fr": "Recevez des rendements"
    },
    "investors_h_s4_body": {
        "es": "Cuando el deudor paga la factura, tu principal más los rendimientos se acreditan automáticamente a tu cuenta.",
        "fr": "Lorsque le débiteur paie la facture, votre principal plus les rendements sont crédités automatiquement sur votre compte."
    },
    "investors_cta_h": {
        "es": "Comienza a invertir en facturas hoy.",
        "fr": "Commencez à investir dans des factures dès aujourd'hui."
    },
    "investors_cta_b": {
        "es": "Abre una cuenta gratuita, explora el mercado y haz tu primera inversión en minutos.",
        "fr": "Ouvrez un compte gratuit, parcourez le marché et effectuez votre premier investissement en quelques minutes."
    },
    "investors_cta_btn": {
        "es": "Abre una cuenta",
        "fr": "Ouvrir un compte"
    },
    "hiw_h1": {
        "es": "De factura a efectivo en cuatro pasos simples.",
        "fr": "De la facture à l'argent liquide en quatre étapes simples."
    },
    "pricing_eyebrow": {
        "es": "Precios",
        "fr": "Tarification"
    },
    "pricing_h1": {
        "es": "Precios simples y transparentes. Sin sorpresas.",
        "fr": "Tarification simple et transparente. Aucune surprise."
    },
    "pricing_lede": {
        "es": "Sin tarifas de configuración. Sin mínimos mensuales. Solo pagas cuando obtienes financiamiento.",
        "fr": "Aucuns frais de configuration. Aucun minimum mensuel. Vous ne payez que lorsque vous êtes financé."
    },
    "contact_eyebrow": {
        "es": "Contacto",
        "fr": "Contact"
    },
    "contact_h1": {
        "es": "Hablemos sobre tu flujo de caja.",
        "fr": "Parlons de votre flux de trésorerie."
    },
    "contact_lede": {
        "es": "Envíanos una nota y te responderemos dentro de un día hábil con una cotización gratuita.",
        "fr": "Envoyez-nous un message et nous vous répondrons dans un jour ouvrable avec un devis gratuit."
    },
    "contact_name": {
        "es": "Tu nombre",
        "fr": "Votre nom"
    },
    "contact_email": {
        "es": "Correo electrónico",
        "fr": "E-mail"
    },
    "contact_company": {
        "es": "Empresa (opcional)",
        "fr": "Entreprise (facultatif)"
    },
    "contact_message": {
        "es": "Cuéntanos sobre tus necesidades de financiamiento de facturas",
        "fr": "Parlez-nous de vos besoins en financement de factures"
    },
    "contact_submit": {
        "es": "Obtén una cotización gratuita",
        "fr": "Obtenir un devis gratuit"
    },
    "contact_thanks_h1": {
        "es": "Gracias — nos pondremos en contacto pronto.",
        "fr": "Merci — nous vous contacterons sous peu."
    },
    "contact_thanks_body": {
        "es": "Normalmente dentro de un día hábil.",
        "fr": "Généralement dans un jour ouvrable."
    },
    "dash_eyebrow": {
        "es": "Panel de control",
        "fr": "Tableau de bord"
    },
    "dash_h1": {
        "es": "Bienvenido a Factorio.",
        "fr": "Bienvenue sur Factorio."
    },
    "dash_lede": {
        "es": "Tu resumen de financiamiento de facturas a simple vista.",
        "fr": "Aperçu de votre financement de factures en un coup d'œil."
    },
    "dash_total_funded": {
        "es": "Total financiado",
        "fr": "Total financé"
    },
    "dash_invoices": {
        "es": "Facturas",
        "fr": "Factures"
    },
    "dash_total_submitted": {
        "es": "total enviado",
        "fr": "total soumis"
    },
    "dash_active": {
        "es": "Financiamiento activo",
        "fr": "Financement actif"
    },
    "dash_seeking": {
        "es": "actualmente buscando inversores",
        "fr": "recherche actuellement des investisseurs"
    },
    "dash_investors": {
        "es": "Inversores",
        "fr": "Investisseurs"
    },
    "dash_active_platform": {
        "es": "activos en la plataforma",
        "fr": "actifs sur la plateforme"
    },
    "dash_browse": {
        "es": "Explorar mercado",
        "fr": "Parcourir le marché"
    },
    "dash_portfolio": {
        "es": "Ver cartera",
        "fr": "Voir le portefeuille"
    },
    "mkt_eyebrow": {
        "es": "Mercado",
        "fr": "Marché"
    },
    "mkt_h1": {
        "es": "Explora oportunidades de facturas.",
        "fr": "Parcourir les opportunités de factures."
    },
    "mkt_count": {
        "es": "facturas actualmente buscando financiamiento",
        "fr": "factures recherchant actuellement un financement"
    },
    "mkt_invest": {
        "es": "Invertir",
        "fr": "Investir"
    },
    "mkt_funded": {
        "es": "financiado",
        "fr": "financé"
    },
    "mkt_term": {
        "es": "plazo",
        "fr": "terme"
    },
    "mkt_advance": {
        "es": "Anticipo",
        "fr": "Avance"
    },
    "mkt_fee": {
        "es": "Comisión / 30d",
        "fr": "Frais / 30j"
    },
    "mkt_est_return": {
        "es": "Rend. est.",
        "fr": "Rend. est."
    },
    "mkt_invoice": {
        "es": "factura",
        "fr": "facture"
    },
    "mkt_seller": {
        "es": "Vendedor",
        "fr": "Vendeur"
    },
    "mkt_empty": {
        "es": "No hay facturas disponibles actualmente para financiamiento.",
        "fr": "Aucune facture n'est actuellement disponible pour le financement."
    },
    "mkt_back": {
        "es": "Volver al mercado",
        "fr": "Retour au marché"
    },
    "port_eyebrow": {
        "es": "Cartera",
        "fr": "Portefeuille"
    },
    "port_h1": {
        "es": "Su cartera de inversiones.",
        "fr": "Votre portefeuille d'investissement."
    },
    "port_total_invested": {
        "es": "Total invertido",
        "fr": "Total investi"
    },
    "port_expected": {
        "es": "Rendimientos esperados",
        "fr": "Rendements attendus"
    },
    "port_active": {
        "es": "Posiciones activas",
        "fr": "Positions actives"
    },
    "port_total": {
        "es": "Total de posiciones",
        "fr": "Total des positions"
    },
    "port_empty": {
        "es": "Aún no hay inversiones.",
        "fr": "Aucun investissement pour l'instant."
    },
    "port_invoice": {
        "es": "Factura",
        "fr": "Facture"
    },
    "port_debtor": {
        "es": "Deudor",
        "fr": "Débiteur"
    },
    "port_invested": {
        "es": "Invertido",
        "fr": "Investi"
    },
    "port_expected_col": {
        "es": "Esperado",
        "fr": "Attendu"
    },
    "port_due": {
        "es": "Vencimiento",
        "fr": "Échéance"
    },
    "port_grade": {
        "es": "Grado",
        "fr": "Note"
    },
    "port_status": {
        "es": "Estado",
        "fr": "Statut"
    },
    "nav_dashboard": {
        "es": "Panel",
        "fr": "Tableau de bord"
    },
    "nav_statement": {
        "es": "Estado de cuenta",
        "fr": "Relevé"
    },
    "nav_autoinvest": {
        "es": "Inversión automática",
        "fr": "Investissement auto"
    },
    "app_viewing_as": {
        "es": "Viendo como",
        "fr": "Affichage en tant que"
    },
    "port_net_return": {
        "es": "Retorno anual neto",
        "fr": "Rendement annuel net"
    },
    "port_interest_received": {
        "es": "Intereses recibidos",
        "fr": "Intérêts reçus"
    },
    "port_writeoffs": {
        "es": "Cancelaciones",
        "fr": "Pertes"
    },
    "port_net_income": {
        "es": "Ingresos netos",
        "fr": "Revenu net"
    },
    "port_account_value": {
        "es": "Valor de la cuenta",
        "fr": "Valeur du compte"
    },
    "port_invested_active": {
        "es": "Inversiones activas",
        "fr": "Investissements actifs"
    },
    "port_expected_outstanding": {
        "es": "Rendimientos esperados pendientes",
        "fr": "Rendements attendus en cours"
    },
    "port_realized": {
        "es": "Rendimientos realizados",
        "fr": "Rendements réalisés"
    },
    "port_aging_title": {
        "es": "Inversiones por estado",
        "fr": "Investissements par statut"
    },
    "port_habits_title": {
        "es": "Hábitos de pago del deudor",
        "fr": "Habitudes de paiement du débiteur"
    },
    "port_col_invoices": {
        "es": "Facturas",
        "fr": "Factures"
    },
    "port_exp_principal": {
        "es": "Principal esperado",
        "fr": "Principal attendu"
    },
    "port_exp_interest": {
        "es": "Interés esperado",
        "fr": "Intérêt attendu"
    },
    "port_col_percentage": {
        "es": "Porcentaje",
        "fr": "Pourcentage"
    },
    "port_col_amount": {
        "es": "Importe",
        "fr": "Montant"
    },
    "port_realized_col": {
        "es": "Realizado",
        "fr": "Réalisé"
    },
    "port_settled_col": {
        "es": "Liquidado el",
        "fr": "Réglé le"
    },
    "port_positions_title": {
        "es": "Todas las posiciones",
        "fr": "Toutes les positions"
    },
    "bkt_in_payment": {
        "es": "En pago",
        "fr": "En paiement"
    },
    "bkt_late_1_14": {
        "es": "1–14 días de retraso",
        "fr": "1–14 jours de retard"
    },
    "bkt_late_15_30": {
        "es": "15–30 días de retraso",
        "fr": "15–30 jours de retard"
    },
    "bkt_late_31_60": {
        "es": "31–60 días de retraso",
        "fr": "31–60 jours de retard"
    },
    "bkt_late_61_120": {
        "es": "61–120 días de retraso",
        "fr": "61–120 jours de retard"
    },
    "bkt_late_120": {
        "es": "120+ días de retraso",
        "fr": "120+ jours de retard"
    },
    "bkt_paid_earlier": {
        "es": "Pagado antes",
        "fr": "Payé plus tôt"
    },
    "bkt_paid_on_time": {
        "es": "Pagado a tiempo",
        "fr": "Payé à temps"
    },
    "bkt_recovered": {
        "es": "Recuperado",
        "fr": "Récupéré"
    },
    "stmt_eyebrow": {
        "es": "Estado de cuenta",
        "fr": "Relevé de compte"
    },
    "stmt_h1": {
        "es": "Su historial de transacciones.",
        "fr": "Votre historique de transactions."
    },
    "stmt_period": {
        "es": "Período",
        "fr": "Période"
    },
    "stmt_from": {
        "es": "Desde",
        "fr": "De"
    },
    "stmt_to": {
        "es": "Hasta",
        "fr": "À"
    },
    "stmt_type": {
        "es": "Tipo",
        "fr": "Type"
    },
    "stmt_all_types": {
        "es": "Todos los tipos",
        "fr": "Tous les types"
    },
    "stmt_counterparty": {
        "es": "Contraparte",
        "fr": "Contrepartie"
    },
    "stmt_invoice_no": {
        "es": "N.º de factura",
        "fr": "N° de facture"
    },
    "stmt_filter": {
        "es": "Filtrar",
        "fr": "Filtrer"
    },
    "stmt_export": {
        "es": "Exportar CSV",
        "fr": "Exporter CSV"
    },
    "stmt_date": {
        "es": "Fecha",
        "fr": "Date"
    },
    "stmt_amount": {
        "es": "Importe",
        "fr": "Montant"
    },
    "stmt_empty": {
        "es": "No se encontraron transacciones.",
        "fr": "Aucune transaction trouvée."
    },
    "txn_investment": {
        "es": "Inversión",
        "fr": "Investissement"
    },
    "txn_dividend": {
        "es": "Dividendo",
        "fr": "Dividende"
    },
    "txn_settlement": {
        "es": "Liquidación",
        "fr": "Règlement"
    },
    "dash_welcome": {
        "es": "Bienvenido de nuevo",
        "fr": "Bienvenue à nouveau"
    },
    "dash_your_overview": {
        "es": "Su resumen",
        "fr": "Votre aperçu"
    },
    "dash_portfolio_value": {
        "es": "Valor de la cartera",
        "fr": "Valeur du portefeuille"
    },
    "dash_net_return": {
        "es": "Retorno neto",
        "fr": "Rendement net"
    },
    "dash_earned": {
        "es": "Ganado hasta la fecha",
        "fr": "Gagné à ce jour"
    },
    "dash_next_settlement": {
        "es": "Próxima liquidación",
        "fr": "Prochain règlement"
    },
    "dash_activity": {
        "es": "Actividad reciente",
        "fr": "Activité récente"
    },
    "dash_no_activity": {
        "es": "No hay actividad reciente.",
        "fr": "Aucune activité récente."
    },
    "dash_platform": {
        "es": "Plataforma",
        "fr": "Plateforme"
    },
    "ai_eyebrow": {
        "es": "Inversión automática",
        "fr": "Investissement auto"
    },
    "ai_h1": {
        "es": "Automatice sus inversiones.",
        "fr": "Automatisez vos investissements."
    },
    "ai_lede": {
        "es": "Establezca sus reglas y deje que Factorio realice ofertas en facturas coincidentes automáticamente.",
        "fr": "Définissez vos règles et laissez Factorio placer des offres sur les factures correspondantes automatiquement."
    },
    "ai_status": {
        "es": "Estado",
        "fr": "Statut"
    },
    "ai_active": {
        "es": "Activo",
        "fr": "Actif"
    },
    "ai_inactive": {
        "es": "Inactivo",
        "fr": "Inactif"
    },
    "ai_min_grade": {
        "es": "Grado de riesgo mínimo",
        "fr": "Note de risque minimale"
    },
    "ai_max_amount": {
        "es": "Máx. por factura",
        "fr": "Max par facture"
    },
    "ai_sectors": {
        "es": "Sectores preferidos",
        "fr": "Secteurs préférés"
    },
    "ai_sectors_hint": {
        "es": "Separados por comas; deje en blanco para todos los sectores.",
        "fr": "Séparés par des virgules ; laissez vide pour tous les secteurs."
    },
    "ai_enable": {
        "es": "Habilitar inversión automática",
        "fr": "Activer l'investissement auto"
    },
    "ai_save": {
        "es": "Guardar configuración",
        "fr": "Enregistrer les paramètres"
    },
    "ai_saved": {
        "es": "Configuración guardada.",
        "fr": "Paramètres enregistrés."
    },
    "mkt_filters": {
        "es": "Filtros",
        "fr": "Filtres"
    },
    "mkt_all": {
        "es": "Todos",
        "fr": "Tous"
    },
    "mkt_sector": {
        "es": "Sector",
        "fr": "Secteur"
    },
    "mkt_risk": {
        "es": "Grado de riesgo",
        "fr": "Note de risque"
    },
    "mkt_max_term": {
        "es": "Plazo máx. (días)",
        "fr": "Durée max (jours)"
    },
    "mkt_min_return": {
        "es": "Retorno mín. %",
        "fr": "Rendement min %"
    },
    "mkt_apply": {
        "es": "Aplicar",
        "fr": "Appliquer"
    },
    "mkt_clear": {
        "es": "Limpiar",
        "fr": "Effacer"
    },
    "mkt_debtor_profile": {
        "es": "Perfil del deudor",
        "fr": "Profil du débiteur"
    },
    "mkt_turnover": {
        "es": "Facturación anual",
        "fr": "Chiffre d'affaires annuel"
    },
    "mkt_registration": {
        "es": "Registro",
        "fr": "Enregistrement"
    },
    "mkt_country": {
        "es": "País",
        "fr": "Pays"
    },
    "nav_triage": {
        "es": "Triage de IA",
        "fr": "Triage IA"
    },
    "nav_assistant": {
        "es": "Informes de IA",
        "fr": "Rapports IA"
    },
    "ai_you": {
        "es": "Tú",
        "fr": "Vous"
    },
    "ai_bot": {
        "es": "Factorio AI",
        "fr": "Factorio AI"
    },
    "ai_send": {
        "es": "Enviar",
        "fr": "Envoyer"
    },
    "ai_thinking": {
        "es": "Pensando…",
        "fr": "Réflexion…"
    },
    "ai_disabled": {
        "es": "El asistente de IA no está configurado (establezca XAI_API_KEY).",
        "fr": "L'assistant IA n'est pas configuré (définissez XAI_API_KEY)."
    },
    "ai_triage_eyebrow": {
        "es": "IA · Triage de solicitudes",
        "fr": "IA · Triage des candidatures"
    },
    "ai_triage_h1": {
        "es": "Obtenga el triage de su factura en un chat",
        "fr": "Faites trier votre facture dans un chat"
    },
    "ai_triage_lede": {
        "es": "Describa su factura y deudor en lenguaje sencillo. El asistente recopila lo que falta, luego da una banda de riesgo indicativa, tasa de anticipo y los documentos que el banco necesitará a continuación.",
        "fr": "Décrivez votre facture et votre débiteur en langage simple. L'assistant collecte ce qui manque, puis donne une bande de risque indicative, un taux d'avance et les documents dont la banque aura besoin ensuite."
    },
    "ai_triage_greeting": {
        "es": "¡Hola! Te ayudaré a clasificar tu factura para financiamiento. Para empezar, dime: qué empresa emitió la factura, quién es el deudor (comprador), el monto de la factura y su fecha de vencimiento.",
        "fr": "Salut ! Je vais vous aider à trier votre facture pour le financement. Pour commencer, dites-moi : quelle entreprise a émis la facture, qui est le débiteur (acheteur), le montant de la facture et sa date d'échéance ?"
    },
    "ai_triage_placeholder": {
        "es": "p. ej. Facturamos a Artel por UZS 480,000,000, vencimiento en 60 días…",
        "fr": "p. ex. Nous avons facturé Artel pour UZS 480 000 000, échéance dans 60 jours…"
    },
    "ai_assistant_eyebrow": {
        "es": "IA · Informes de cartera",
        "fr": "IA · Rapports de portefeuille"
    },
    "ai_assistant_h1": {
        "es": "Pregunte cualquier cosa sobre su cartera",
        "fr": "Posez n'importe quelle question sur votre portefeuille"
    },
    "ai_assistant_lede": {
        "es": "El asistente responde desde tus propias posiciones — rendimiento neto, intereses pendientes, concentración por deudor o sector, próximos vencimientos y más. Basado en los datos en vivo de tu cartera.",
        "fr": "L'assistant répond à partir de vos propres positions — rendement net, intérêts en suspens, concentration par débiteur ou secteur, règlements à venir et plus. Basé sur les données en direct de votre portefeuille."
    },
    "ai_assistant_greeting": {
        "es": "¡Hola! Puedo responder preguntas sobre tu cartera — rendimientos, posiciones pendientes, concentración y vencimientos. ¿Qué te gustaría saber?",
        "fr": "Bonjour ! Je peux répondre à des questions sur votre portefeuille — rendements, positions en suspens, concentration et règlements. Que souhaitez-vous savoir ?"
    },
    "ai_assistant_placeholder": {
        "es": "p. ej. ¿Cuál es mi exposición a la construcción? ¿Qué posiciones están vencidas?",
        "fr": "p. ex. Quelle est mon exposition à la construction ? Quelles positions sont en retard ?"
    }
}
