"""Generate the Spanish/French i18n overlay with Grok (x.ai).

Reads the English values from ``utils.i18n.TRANSLATIONS``, translates each into
Spanish and French in batches, and writes ``utils/i18n_es_fr.py`` (an ``EXTRA``
dict merged into TRANSLATIONS at import). English stays the default and the
fallback; only ``es``/``fr`` are produced here.

    python -m scripts.translate_i18n
    python -m scripts.translate_i18n --batch 40

Requires XAI_API_KEY (config via utils.config.settings, read by utils.ai).
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from utils.ai import chat
from utils.i18n import TRANSLATIONS

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "utils" / "i18n_es_fr.py"

SYSTEM = (
    "You are a professional UI translator for a fintech invoice-financing "
    "platform. Translate the given English UI strings into Spanish (es) and "
    "French (fr). Rules: preserve markdown (**bold**, `code`), HTML entities "
    "(e.g. &rarr;, &#9881;), any placeholders/braces, currency codes (UZS, EUR, "
    "USD, GBP), and brand/product names exactly (Factorio, Consistente, "
    "SoliqOnline, Didox, CRIF, DIFC, Grok, x.ai, Universalbank, OzPlanet, "
    "FinMakon). Match tone and keep length similar. Return STRICT JSON only: an "
    "object mapping each input key to an object {\"es\": \"...\", \"fr\": \"...\"}. "
    "No commentary, no code fences."
)


def _parse_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-z]*\n?|\n?```$", "", text.strip())
    m = re.search(r"\{.*\}", text, re.S)
    return json.loads(m.group(0) if m else text)


def translate(batch: int = 40) -> dict:
    keys = list(TRANSLATIONS.keys())
    extra: dict[str, dict] = {}
    for i in range(0, len(keys), batch):
        chunk = keys[i:i + batch]
        src = {k: TRANSLATIONS[k].get("en", k) for k in chunk}
        n = i // batch + 1
        total = (len(keys) + batch - 1) // batch
        print(f"  batch {n}/{total} ({len(chunk)} keys)…", end=" ", flush=True)
        reply = chat(
            [{"role": "system", "content": SYSTEM},
             {"role": "user", "content": json.dumps(src, ensure_ascii=False)}],
            temperature=0, max_tokens=4000,
        )
        try:
            got = _parse_json(reply)
        except Exception as e:  # noqa: BLE001
            print(f"parse failed ({e}); skipping batch")
            continue
        added = 0
        for k in chunk:
            v = got.get(k)
            if isinstance(v, dict) and v.get("es") and v.get("fr"):
                extra[k] = {"es": v["es"], "fr": v["fr"]}
                added += 1
        print(f"{added}/{len(chunk)} ok")
    return extra


def write_overlay(extra: dict) -> None:
    header = ('"""AUTO-GENERATED by scripts/translate_i18n.py — Spanish/French '
              'overlay.\n\nMerged into utils.i18n.TRANSLATIONS at import. '
              'Regenerate with:\n    python -m scripts.translate_i18n\n"""\n\n')
    OUT.write_text(header + "EXTRA = " + json.dumps(extra, ensure_ascii=False, indent=4) + "\n",
                   encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--batch", type=int, default=40)
    args = ap.parse_args()
    print(f"Translating {len(TRANSLATIONS)} keys → es/fr via Grok…")
    extra = translate(args.batch)
    write_overlay(extra)
    print(f"Wrote {OUT.relative_to(ROOT)} with {len(extra)}/{len(TRANSLATIONS)} keys.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
